"""outbox model updates : made model into 3.

Revision ID: 1933ee2782ac
Revises: 181b0ea95ffc
Create Date: 2025-12-09 18:46:25.988316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1933ee2782ac'
down_revision: Union[str, Sequence[str], None] = '181b0ea95ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
